name: Render Ping Bot

on:
  schedule:
    # Every 10 minutes, all day
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Crypto Exchange Bot
        run: curl -I https://cryptoexchangebot.onrender.com

      - name: Ping Firstlight Frontend
        run: curl -I https://firstlight-web.onrender.com

      - name: Ping Firstlight API
        run: curl -I https://firstlighthq.onrender.com
