name: Render Ping Bot

on:
  schedule:
    # Every 14 minutes between 08:00 and 20:00 UTC
    - cron: '*/13 5-16 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Crypto Exchange Bot
        run: curl -I https://cryptoexchangebot.onrender.com
